# Generated by Django 4.0.1 on 2022-01-06 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=15)),
                ('dokon_nomi', models.CharField(max_length=15)),
                ('maxsulot_turi', models.CharField(blank=True, max_length=30)),
                ('joyalshish', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('brend_nomi', models.CharField(max_length=35)),
                ('narx', models.IntegerField()),
                ('miqdori', models.IntegerField()),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=15)),
                ('dokon_nomi', models.CharField(max_length=15)),
                ('joylashish', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('qarz', models.IntegerField(default=0)),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.ombor')),
            ],
        ),
    ]
